import 'package:flutter/material.dart';

const colorPrimary = Color(0xffFF7D33);
const Color kPrimaryColor =  Color(0xffFF7D33);
const Color kSecondaryColor = Color(0xffCACACA);
const Color backGroundColor = Color(0xffFFFFFF);
const Color kScaffoldBackground = Color(0xffFFF3E9);
const Color p1Color = Color(0xff6E798C);
const Color TextColor = Color(0xff7C7C7C);
const Color white = Color(0xffFFFFFF);
const Color h1Color = Color(0xff343D48);
const Color buttonColor = Color(0xff7CC344);
const Color bottonColor2 = Color(0xfff5f5f5);
const Color bgColor = Color.fromRGBO(255, 125, 51, 0.15);
const Color btn = Color(0xff109D03);
const Color b1Color = Color(0xff6363BE);
const Color blueColor = Color(0xff32326F);
const Color blackColor = Color(0xff232323);
const Color textFiledColor = Color(0xffCACACA);
const Color grey = Color(0xffF5F5F5FF);
const Color grey300 = Color(0xffE0E0E0FF);
const Color CAMERABORDERCOLOR = Color(0xffECF1F6);
const Color black = Color(0xff262626);
const Color red = Color(0xffFF1313);
const Color logoutclr = Color(0xffC70000);
const Color dividerr = Color(0xffCACACA);
const Color DIVIDER_2 = Color(0xffC0BCBC);
const Color TEXTFIELD_BORDER_COLOR = Color(0xffF2F2F2);
const Color TEXTFIELD_BACKGROUND_COLOR = Color(0xffFBFBFB);
const Color graphcolor = Color(0xffFAA82C);
const Color EDITCOLOR = Color(0xff618E00);
const Color BORDERCOLOR = Color(0xffE9ECEF);
const Color BUTTONBORDERCOLOR = Color(0xffF5F5F5);
const Color CANCELCOLOR = Color(0XFFC0BCBC);
const Color CALLBTNCOLOR = Color(0XFFFFF0E8);
const Color divider = Color(0xffF2F2F2);
const Color BACK_ICON_BACKGROUND_COLOR = Color(0xFFEFEFEF);
const Color GREEN_COLOR = Color(0xFF45D700);
const Color GREY_COLOR = Color(0xFFC4C4C4);
const Color BANK_ACCOUNT_BORDER_COLOR = Color(0xFF65D176);
const Color CHECK_BACKGROUND_COLOR = Color(0xFF4CAF50);
const Color CHECK_BORDER_COLOR = Color(0xFFC3C3C3);


